version: 2.0.0-alpha.{build}+{branch}
init:
  - git config --global core.autocrlf true
clone_depth: 1
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
build_script:
  - ps: .\build.ps1
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
deploy: off
os: Visual Studio 2017
artifacts:
  - path: artifacts/*.nupkg
    name: Packages
    type: NuGetPackages
