build_script:
  - ps: iwr https://get.dot.net/v1/dotnet-install.ps1 -out dotnet-install.ps1; ./dotnet-install.ps1 -Version 2.2.100
  - ps: .\docs\generate.ps1 -Verbose
  - ps: .\docs\push.ps1 -AppVeyor
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
  GITHUB_ACCESS_TOKEN:
    secure: 7gza5cyC0Fwp5LcFPz9dGMcHXP2jxbrnu7er9R/HkdvnhzGJVADvOtfYO7+Vow5p
test: off
os: Visual Studio 2017
branches:
  only:
    - master
