build_script:
  - ps: iwr https://get.dot.net/v1/dotnet-install.ps1 -out dotnet-install.ps1; ./dotnet-install.ps1 -Version 2.2.100
  - ps: .\docs\generate.ps1 -Verbose
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
os: Visual Studio 2017
branches:
  only:
    - master
after_deploy:
  - ps: .\docs\push.ps1 -AppVeyor
