name: $(Date:yyMMdd).$(Rev:r)

trigger:
- '*'

pr:
- '*'

variables:
# Set this to an empty value for pull-request builds
- name: kv-access-token
  value: ''
# This contains secrets for accessing code-signing certificates during an official build
- group: AzureKeyVault
# Skip the package warm up step
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: 1

jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - task: DotNetCoreInstaller@0
    displayName: Install .NET Core 2.2
    inputs:
      version: '2.2.102'
  - powershell: ./build.ps1 -ci /p:AzureKeyVaultClientSecret=$(kv-access-token)
    displayName: Invoke build.ps1
  - task: PublishTestResults@2
    displayName: Upload test results
    condition: always()
    continueOnError: true
    inputs:
      testRunTitle: Windows
      testRunner: vstest
      testResultsFiles: '**/*.trx'
  - task: PublishBuildArtifacts@1
    displayName: Publish artifacts
    inputs:
      pathtoPublish: 'artifacts/'
      artifactName: 'Packages'
- job: Linux
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: DotNetCoreInstaller@0
    displayName: Install .NET Core 2.2
    inputs:
      version: '2.2.102'
  - script: ./build.ps1 -ci
    displayName: Invoke build.ps1
  - task: PublishTestResults@2
    displayName: Upload test results
    condition: always()
    continueOnError: true
    inputs:
      testRunTitle: Linux
      testRunner: vstest
      testResultsFiles: '**/*.trx'
